spring:
  datasource:
    url: jdbc:mysql://${db.url:localhost}:${db.port:3306}/manage_employee?createDatabaseIfNotExist=true
    username: ${db.username:root}
    password: ${db.password:123456}
  jpa:
    open-in-view: false
security:
  config:
    time: 7200
    prefix: "Bearer "
    key: "$2y$12$Gdkq1gKYyOi/1X38N8DSuewgnvK/6XWN44IaJpM0N46TCPqovS/JK"
    header: "Authorization"